export const email = "mangaloreselfdriverentalcars@gmail.com"
export const phone = "9113217773"
export const instagram = "#"
export const twitter = "#"
export const facebook = "#"
export const youtube = "#"
